/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package daftarmahasiswa;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class Menu extends javax.swing.JFrame {

    private DefaultTableModel dtm;
    private Boolean isUpdate = false;
    private int selectedID = -1;
    private ArrayList<Mahasiswa> listMhs;

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        listMhs = new ArrayList<>();
        //Dummy
        listMhs.add(new Mahasiswa("1111", "Aaaa", "A"));
        listMhs.add(new Mahasiswa("2222", "Bbbb", "B"));
        listMhs.add(new Mahasiswa("3333", "Cccc", "C"));
        // Set Table
        txtFieldtabel.setModel(setTable());
        // Hide Delete button
        txtdelete.setVisible(false);
    }

    public final DefaultTableModel setTable() {
        Object[] column = {"NIM", "Nama", "Nilai"};
        DefaultTableModel dataTabel = new DefaultTableModel(null, column);
        for (int i = 0; i < listMhs.size(); i++) {
            Object[] row = new Object[3];
            row[0] = listMhs.get(i).getNim();
            row[1] = listMhs.get(i).getNama();
            row[2] = listMhs.get(i).getNilai();

            dataTabel.addRow(row);
        }

        return dataTabel;
    }

    public void insertData() {
        // Get Data
        String nim = txtfieldnim.getText();
        String nama = txtfieldnama.getText();
        String nilai = txtfieldnilai.getText();
        
        //pengecekan kondisi inputan menggunakan isBlank untuk melihat apakah di dalam 
        //kolom terdapat inputan atau tidak
        //jika kolom nim / nama / nilai kosong
        if (nim.isBlank()||nama.isBlank()||nilai.isBlank())
        {
            //manampilkan hasil
            System.out.println("Insert Failed!");
            JOptionPane.showMessageDialog(null, "Input data gagal!!");
        }
        //jika tidak kosong
        else
        {
            // input data to table
            listMhs.add(new Mahasiswa(nim, nama, nilai));
            
            // update the table after input the data
            txtFieldtabel.setModel(setTable());
               
            //output
            System.out.println("Insert Success!");
            JOptionPane.showMessageDialog(null, "Data berhasil ditambahkan!");
        }

        
    }

    public void updateData() {
        // Get Data
        String nim = txtfieldnim.getText();
        String nama = txtfieldnama.getText();
        String nilai = txtfieldnilai.getText();
        //System.out.println(nim + nama + nilai);

        listMhs.get(selectedID).setNim(nim);
        listMhs.get(selectedID).setNama(nama);
        listMhs.get(selectedID).setNilai(nilai);
        
        // update the table after update the data
        txtFieldtabel.setModel(setTable());

        System.out.println("Update Success!");
        JOptionPane.showMessageDialog(null, "Data berhasil diubah!");
    }

    public void deleteData() 
    {
        // Get Data
        String nim = txtfieldnim.getText();
        String nama = txtfieldnama.getText();
        String nilai = txtfieldnilai.getText();
        
        // menghapus data
        listMhs.remove(selectedID);        
        
        // update table after delete the data        
        txtFieldtabel.setModel(setTable());
        
        System.out.println("Delete Success!");
        JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txttitle = new javax.swing.JLabel();
        txtadd = new javax.swing.JButton();
        txtfieldnim = new javax.swing.JTextField();
        txtnim = new javax.swing.JLabel();
        txtnama = new javax.swing.JLabel();
        txtfieldnama = new javax.swing.JTextField();
        txtnilai = new javax.swing.JLabel();
        txtfieldnilai = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtFieldtabel = new javax.swing.JTable();
        txtdelete = new javax.swing.JButton();
        txtcancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txttitle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txttitle.setText("Daftar Mahasiswa");

        txtadd.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtadd.setText("Add");
        txtadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaddActionPerformed(evt);
            }
        });

        txtfieldnim.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtfieldnim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfieldnimActionPerformed(evt);
            }
        });

        txtnim.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtnim.setText("NIM");

        txtnama.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtnama.setText("Nama");

        txtfieldnama.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtfieldnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfieldnamaActionPerformed(evt);
            }
        });

        txtnilai.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtnilai.setText("Nilai");

        txtfieldnilai.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtfieldnilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfieldnilaiActionPerformed(evt);
            }
        });

        txtFieldtabel.setAutoCreateRowSorter(true);
        txtFieldtabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtFieldtabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        txtFieldtabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtFieldtabel.setUpdateSelectionOnSort(false);
        txtFieldtabel.setVerifyInputWhenFocusTarget(false);
        txtFieldtabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFieldtabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(txtFieldtabel);

        txtdelete.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtdelete.setText("Delete");
        txtdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdeleteActionPerformed(evt);
            }
        });

        txtcancel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtcancel.setText("Cancel");
        txtcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txttitle)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(txtnama)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtfieldnama, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(txtnim)
                                    .addGap(55, 55, 55)
                                    .addComponent(txtfieldnim, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(txtnilai)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtfieldnilai, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtadd)
                            .addComponent(txtdelete)
                            .addComponent(txtcancel))))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(txttitle)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfieldnim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnim)
                    .addComponent(txtadd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfieldnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnama)
                    .addComponent(txtcancel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfieldnilai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnilai)
                    .addComponent(txtdelete))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtfieldnimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfieldnimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfieldnimActionPerformed

    private void txtfieldnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfieldnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfieldnamaActionPerformed

    private void txtfieldnilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfieldnilaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfieldnilaiActionPerformed

    private void txtaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaddActionPerformed
        // TODO add your handling code here:
        if (isUpdate == false)
            insertData();
        else {
            updateData();
            txtadd.setText("Add");
            txtdelete.setVisible(false);
            this.isUpdate = false;
        }
    }//GEN-LAST:event_txtaddActionPerformed

    private void txtFieldtabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFieldtabelMouseClicked
        // TODO add your handling code here:
        this.isUpdate = true;

        //Get Selected Data
        int row = txtFieldtabel.getSelectedRow();
        String selectedNim = (txtFieldtabel.getModel().getValueAt(row, 0).toString());
        String selectedNama = (txtFieldtabel.getModel().getValueAt(row, 1).toString());
        String selectedNilai = (txtFieldtabel.getModel().getValueAt(row, 2).toString());

        for (int i = 0; i < listMhs.size(); i++) {
            if (selectedNim.equals(listMhs.get(i).getNim())) {
                selectedID = i;
                break;
            }
        }

        //System.out.println(selectedID);
        txtfieldnim.setText(selectedNim);
        txtfieldnama.setText(selectedNama);
        txtfieldnilai.setText(selectedNilai);

        txtadd.setText("Update");
        txtdelete.setVisible(true);
    }//GEN-LAST:event_txtFieldtabelMouseClicked

    private void txtdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdeleteActionPerformed
        // TODO add your handling code here:
        if (isUpdate == true) {
            deleteData();
            txtadd.setText("Add");
            txtdelete.setVisible(false);
            this.isUpdate = false;
        }
    }//GEN-LAST:event_txtdeleteActionPerformed

    private void txtcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcancelActionPerformed
        // TODO add your handling code here:
        txtadd.setText("Add");
        txtdelete.setVisible(false);
        this.isUpdate = false;
        
        //manmpilkan output
        JOptionPane.showMessageDialog(null, "Proses berhasil di cancel!");
    }//GEN-LAST:event_txtcancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable txtFieldtabel;
    private javax.swing.JButton txtadd;
    private javax.swing.JButton txtcancel;
    private javax.swing.JButton txtdelete;
    private javax.swing.JTextField txtfieldnama;
    private javax.swing.JTextField txtfieldnilai;
    private javax.swing.JTextField txtfieldnim;
    private javax.swing.JLabel txtnama;
    private javax.swing.JLabel txtnilai;
    private javax.swing.JLabel txtnim;
    private javax.swing.JLabel txttitle;
    // End of variables declaration//GEN-END:variables
}
